name: Cypress Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install cypress@12.17.4 --save-dev --legacy-peer-deps
          npm install start-server-and-test --save-dev --legacy-peer-deps
          npm install @faker-js/faker@7.6.0 --save-dev --legacy-peer-deps

      - name: Run Cypress tests
        run: |
          mkdir -p cypress/reports/html
          npm run test:e2e
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Debug - List Reports
        if: always()
        run: |
          echo "Listing reports directory:"
          ls -la cypress/reports/
          echo "Listing HTML reports:"
          ls -la cypress/reports/html/

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: |
            cypress/reports/**/*
            cypress/reports/html/**/*
          retention-days: 30

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress/reports
          enable_jekyll: false
          keep_files: false
          force_orphan: true
