name: Cypress Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install --force
          npm install start-server-and-test wait-on --save-dev

      - name: Build and start Angular app
        run: |
          npm start & npx wait-on http://localhost:4200
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Run Cypress tests
        run: |
          mkdir -p cypress/reports
          npm run cy:report

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/html
          keep_files: false
