name: Cypress Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g cypress
          npm install start-server-and-test --save-dev --legacy-peer-deps

      - name: Run Cypress tests
        run: |
          npm start & npx wait-on http://localhost:4200 && npx cypress run --spec "cypress/e2e/{apiTest.spec.js,firstTest.spec.ts,testWithPageObject.ts}" --reporter cypress-mochawesome-reporter
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports
          retention-days: 30

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/html
          keep_files: false
          allow_empty_commit: true
          force_orphan: true
